### PR TITLE
fix

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
I pushed https://github.com/YunoHost/yunohost/commit/51d5dca03387d18842388379b5177b6e83833e4d as an attempt to fix an edge case that makes everything explode ... Though I don't know if it's gonna fix everything (there are underlying existential questions related to the fact that phpversion is defined as a global during install even before ynh_add_fpm_config is set, and to the apt dependency management...)

**Comment by ericgaspar** [comment]
I am wondering why we don't get the same issue with this PR where we are also testing multiple PHP versions : https://github.com/YunoHost-Apps/my_webapp_ynh/pull/70/files

**Comment by alexAubin** [comment]
Uh yeah good question, I was thinking maybe there's a ynh_install_app_dependencies but nope ...

**Comment by ericgaspar** [comment]
It as maybe to do with 4.3 changes... lets try to relaunch a test.

**Comment by ericgaspar** [comment]
> It as maybe to do with 4.3 changes... lets try to relaunch a test.

with 4.3 we get the same error for my_webapp:   https://ci-apps-dev.yunohost.org/ci/job/3762

**Pull request merged**
